### ISSUE TITLE
Sharing iP code quality feedback [for @minghowC]

### ISSUE THREAD

**Issue by nus-se-script** [minghowC/ip#1]
@minghowC We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

Example from [`src/main/java/Deadline.java` lines `10-10`](https://github.com/minghowC/ip/blob/1b63e7c9a401e72962b0599ccc925272f1808476/src/main/java/Deadline.java#L10..L10):

```java

[TAB][TAB]try{

```

Example from [`src/main/java/Deadline.java` lines `11-11`](https://github.com/minghowC/ip/blob/1b63e7c9a401e72962b0599ccc925272f1808476/src/main/java/Deadline.java#L11..L11):

```java

[TAB][TAB][TAB]this.deadline = LocalDate.parse(deadline);

```

Example from [`src/main/java/Deadline.java` lines `12-12`](https://github.com/minghowC/ip/blob/1b63e7c9a401e72962b0599ccc925272f1808476/src/main/java/Deadline.java#L12..L12):

```java

[TAB][TAB]} catch (DateTimeParseException e) {

``` 

**Suggestion:** As specified by the coding standard, use spaces instead of tabs.

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

Example from [`src/main/java/IreneAI.java` lines `15-99`](https://github.com/minghowC/ip/blob/1b63e7c9a401e72962b0599ccc925272f1808476/src/main/java/IreneAI.java#L15..L99):

```java

    public static void main(String[] args) throws DukeException {
        Scanner scanner = new Scanner(System.in);

        String chatbotName = "IreneAI";
        dividingLine(LINE);
        System.out.println(" Hello! I'm " + chatbotName);
        System.out.println(" What can I do for you?");
        dividingLine(LINE);

        while (true) {
            System.out.println("You: ");
            String userInput = scanner.nextLine();
            String[] splitInputs = userInput.split(" ");
            Command command = Command.getCommand(splitInputs[0]);
            String argument = splitInputs.length > 1 ? splitInputs[1] : "";
            dividingLine(LINE);

            try {
                switch (command) {
                    case BYE:
                        System.out.println(" Bye. Hope to see you again soon!");
                        dividingLine(LINE);
                        return;
                    case TODO:
                        if (argument.isEmpty()) {
                            throw new DukeException("The description of a todo cannot be empty.");
                        }
                        handleTodo(argument);
                        break;
                    case DEADLINE:
                        // Checks command contains "/by"
                        boolean hasBy = userInput.split(" /by ").length > 1;
                        // Makes sure arguments are at least 3 (e.g. command, subject, deadline)
                        boolean isValid = hasBy && splitInputs.length > 2;
                        if (!isValid) {
                            throw new DukeException("The deadline command requires both description and time inputs, separated by ' /by '");
                        }
                        handleDeadline(userInput);
                        break;
                    case EVENT:
                        // Checks command contains '/from'
                        boolean hasFrom = userInput.split(" /from ").length > 1;
                        // Checks command contains '/to'
                        boolean hasTo = userInput.split(" /to ").length > 1;
                        isValid = hasTo && hasFrom && splitInputs.length > 3;
                        if (!isValid) {
                            throw new DukeException("The event command requires a description, from when, and to when"
                                    + ".\n" + "For example, event project meeting /from Mon 2pm /to 4pm");
                        }
                        handleEvent(userInput);
                        break;
                    case LIST:
                        listTasks();
                        break;
                    case UNMARK:
                        if (argument.isEmpty()) {
                            throw new DukeException("You must specific which task to unmark (in number).");
                        }
                        handleUnmark(userInput);
                        break;
                    case MARK:
                        // future works: index out of bound cases
                        if (argument.isEmpty()) {
                            throw new DukeException("You must specific which task to mark (in number).");
                        }
                        handleMark(userInput);
                        break;
                    case DELETE:
                        if (argument.isEmpty()) {
                            throw new DukeException("You must specific which task to mark (in number).");
                        }
                        handleDelete(userInput);
                        break;
                    case INVALID:
                        //Default error handling
                    default:
                        throw new DukeException("I don't get what you mean.. (╥﹏╥)");
                }
            } catch (DukeException e) {
                dividingLine(LINE);
                System.out.println("OOPS!! " + e.getMessage());
                dividingLine(LINE);
            }
        }
    }

``` 

**Suggestion:** Consider applying [SLAP (and other abstraction mechanisms)](https://nus-cs2103-ay2324s2.github.io/website//se-book-adapted/chapters/codeQuality.html#guideline-maximise-readability) to shorten methods e.g., extract some code blocks into separate methods. You may ignore this suggestion if you think a longer method is justified in a particular case.

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

No easy-to-detect issues :+1: 

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by minghowC** [comment]
Done
